### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by dolmen** [CPAN-API/github-meets-cpan#8]
The site is unreachable.

Cc: @neilbowers

**Comment by oalders** [comment]
We're getting close to launching this.  We'll be hosting it under metapcan.org, but we need another hostname for it.  Thoughts?  hackers.metacpan.org?

**Comment by oalders** [comment]
cc @ranguard ^^

**Comment by neilbowers** [comment]
* githubbers
* gits
* github-meets
* repomenandwomen
* gmc
* github

**Comment by xsawyerx** [comment]
Best keep it genderless.

**Comment by dolmen** [comment]
github.meet.metacpan.org

**Comment by ranguard** [comment]
We are going for gh.metacapn.org - it's 95% configured (https://github.com/CPAN-API/metacpan-puppet/pull/79 carton/starman etc installed, mongodb installed, nginx configured. DNS and Fastly CDN also done) @oalders just needs to get github credentials deployed and a few other tweaks.

**Comment by ranguard** [comment]
http://gh.metacpan.org/ is now live and on an hourly cron to upgrade

**Comment by neilbowers** [comment]
:+1:

**Comment by ranguard** [comment]
I should mention it's also many times faster ( thanks to Fastly CDN )

**Comment by neilbowers** [comment]
Oh well, in that case: :+2:

**Comment by dolmen** [comment]
:clap:
